name: folium
channels:
  - conda-forge
dependencies:
  - basemap
  - basemap-data
  - folium
  - geopandas
  - geopy
  - geos
  - ipyleaflet
  - jupyterlab
  - jupyterlab-spreadsheet-editor
  - jupyterlab_server
  - jupyterlab_widgets
  - kagglehub
  - leafmap
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - pandas
  - plotly
  - proj=9.4.1
  - pyproj=3.6.1
  - pyshp
  - python=3.12.7
  - seaborn
  - seaborn-base
  - shapely
  - tqdm
  - xyzservices