name: folium
channels:
  - conda-forge
dependencies:
  - basemap
  - basemap-data
  - folium
  - geopandas
  - jupyterlab
  - jupyterlab-spreadsheet-editor
  - jupyterlab_widgets
  - kagglehub
  - leafmap
  - pandas
  - plotly
  - python=3.12.7
  - shapely
  - tqdm
  - xyzservices